// Code generated by protoc-gen-go. DO NOT EDIT.
// source: backup.proto

package backup

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BackupFile_BackupState int32

const (
	BackupFile_UNKNOWN       BackupFile_BackupState = 0
	BackupFile_NOT_BACKED_UP BackupFile_BackupState = 1
	BackupFile_BACKED_UP     BackupFile_BackupState = 2
	BackupFile_MISSING       BackupFile_BackupState = 3
)

var BackupFile_BackupState_name = map[int32]string{
	0: "UNKNOWN",
	1: "NOT_BACKED_UP",
	2: "BACKED_UP",
	3: "MISSING",
}

var BackupFile_BackupState_value = map[string]int32{
	"UNKNOWN":       0,
	"NOT_BACKED_UP": 1,
	"BACKED_UP":     2,
	"MISSING":       3,
}

func (x BackupFile_BackupState) String() string {
	return proto.EnumName(BackupFile_BackupState_name, int32(x))
}

func (BackupFile_BackupState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{2, 0}
}

type Token struct {
	JsonToken            []byte   `protobuf:"bytes,1,opt,name=json_token,json=jsonToken,proto3" json:"json_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{0}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetJsonToken() []byte {
	if m != nil {
		return m.JsonToken
	}
	return nil
}

type Config struct {
	LastBackup           int64         `protobuf:"varint,2,opt,name=last_backup,json=lastBackup,proto3" json:"last_backup,omitempty"`
	Files                []*BackupFile `protobuf:"bytes,3,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{1}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLastBackup() int64 {
	if m != nil {
		return m.LastBackup
	}
	return 0
}

func (m *Config) GetFiles() []*BackupFile {
	if m != nil {
		return m.Files
	}
	return nil
}

type BackupFile struct {
	Path                 string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	DateSeen             int64                  `protobuf:"varint,2,opt,name=date_seen,json=dateSeen,proto3" json:"date_seen,omitempty"`
	State                BackupFile_BackupState `protobuf:"varint,3,opt,name=state,proto3,enum=backup.BackupFile_BackupState" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *BackupFile) Reset()         { *m = BackupFile{} }
func (m *BackupFile) String() string { return proto.CompactTextString(m) }
func (*BackupFile) ProtoMessage()    {}
func (*BackupFile) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{2}
}

func (m *BackupFile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BackupFile.Unmarshal(m, b)
}
func (m *BackupFile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BackupFile.Marshal(b, m, deterministic)
}
func (m *BackupFile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BackupFile.Merge(m, src)
}
func (m *BackupFile) XXX_Size() int {
	return xxx_messageInfo_BackupFile.Size(m)
}
func (m *BackupFile) XXX_DiscardUnknown() {
	xxx_messageInfo_BackupFile.DiscardUnknown(m)
}

var xxx_messageInfo_BackupFile proto.InternalMessageInfo

func (m *BackupFile) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *BackupFile) GetDateSeen() int64 {
	if m != nil {
		return m.DateSeen
	}
	return 0
}

func (m *BackupFile) GetState() BackupFile_BackupState {
	if m != nil {
		return m.State
	}
	return BackupFile_UNKNOWN
}

type TokenRequest struct {
	Token                *Token   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenRequest) Reset()         { *m = TokenRequest{} }
func (m *TokenRequest) String() string { return proto.CompactTextString(m) }
func (*TokenRequest) ProtoMessage()    {}
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{3}
}

func (m *TokenRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenRequest.Unmarshal(m, b)
}
func (m *TokenRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenRequest.Marshal(b, m, deterministic)
}
func (m *TokenRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenRequest.Merge(m, src)
}
func (m *TokenRequest) XXX_Size() int {
	return xxx_messageInfo_TokenRequest.Size(m)
}
func (m *TokenRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenRequest proto.InternalMessageInfo

func (m *TokenRequest) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type TokenResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenResponse) Reset()         { *m = TokenResponse{} }
func (m *TokenResponse) String() string { return proto.CompactTextString(m) }
func (*TokenResponse) ProtoMessage()    {}
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{4}
}

func (m *TokenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenResponse.Unmarshal(m, b)
}
func (m *TokenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenResponse.Marshal(b, m, deterministic)
}
func (m *TokenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenResponse.Merge(m, src)
}
func (m *TokenResponse) XXX_Size() int {
	return xxx_messageInfo_TokenResponse.Size(m)
}
func (m *TokenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TokenResponse proto.InternalMessageInfo

type StatsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsRequest) Reset()         { *m = StatsRequest{} }
func (m *StatsRequest) String() string { return proto.CompactTextString(m) }
func (*StatsRequest) ProtoMessage()    {}
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{5}
}

func (m *StatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsRequest.Unmarshal(m, b)
}
func (m *StatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsRequest.Marshal(b, m, deterministic)
}
func (m *StatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsRequest.Merge(m, src)
}
func (m *StatsRequest) XXX_Size() int {
	return xxx_messageInfo_StatsRequest.Size(m)
}
func (m *StatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatsRequest proto.InternalMessageInfo

type StatsResponse struct {
	Stats                []*Stat  `protobuf:"bytes,1,rep,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatsResponse) Reset()         { *m = StatsResponse{} }
func (m *StatsResponse) String() string { return proto.CompactTextString(m) }
func (*StatsResponse) ProtoMessage()    {}
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{6}
}

func (m *StatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatsResponse.Unmarshal(m, b)
}
func (m *StatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatsResponse.Marshal(b, m, deterministic)
}
func (m *StatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatsResponse.Merge(m, src)
}
func (m *StatsResponse) XXX_Size() int {
	return xxx_messageInfo_StatsResponse.Size(m)
}
func (m *StatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatsResponse proto.InternalMessageInfo

func (m *StatsResponse) GetStats() []*Stat {
	if m != nil {
		return m.Stats
	}
	return nil
}

type Stat struct {
	State                BackupFile_BackupState `protobuf:"varint,1,opt,name=state,proto3,enum=backup.BackupFile_BackupState" json:"state,omitempty"`
	Count                int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Stat) Reset()         { *m = Stat{} }
func (m *Stat) String() string { return proto.CompactTextString(m) }
func (*Stat) ProtoMessage()    {}
func (*Stat) Descriptor() ([]byte, []int) {
	return fileDescriptor_65240d19de191688, []int{7}
}

func (m *Stat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stat.Unmarshal(m, b)
}
func (m *Stat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stat.Marshal(b, m, deterministic)
}
func (m *Stat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stat.Merge(m, src)
}
func (m *Stat) XXX_Size() int {
	return xxx_messageInfo_Stat.Size(m)
}
func (m *Stat) XXX_DiscardUnknown() {
	xxx_messageInfo_Stat.DiscardUnknown(m)
}

var xxx_messageInfo_Stat proto.InternalMessageInfo

func (m *Stat) GetState() BackupFile_BackupState {
	if m != nil {
		return m.State
	}
	return BackupFile_UNKNOWN
}

func (m *Stat) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("backup.BackupFile_BackupState", BackupFile_BackupState_name, BackupFile_BackupState_value)
	proto.RegisterType((*Token)(nil), "backup.Token")
	proto.RegisterType((*Config)(nil), "backup.Config")
	proto.RegisterType((*BackupFile)(nil), "backup.BackupFile")
	proto.RegisterType((*TokenRequest)(nil), "backup.TokenRequest")
	proto.RegisterType((*TokenResponse)(nil), "backup.TokenResponse")
	proto.RegisterType((*StatsRequest)(nil), "backup.StatsRequest")
	proto.RegisterType((*StatsResponse)(nil), "backup.StatsResponse")
	proto.RegisterType((*Stat)(nil), "backup.Stat")
}

func init() { proto.RegisterFile("backup.proto", fileDescriptor_65240d19de191688) }

var fileDescriptor_65240d19de191688 = []byte{
	// 398 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xcd, 0xd6, 0x75, 0xa8, 0xc7, 0x76, 0x09, 0xa3, 0x22, 0x59, 0x20, 0xc0, 0x5a, 0x24, 0xe4,
	0x53, 0x0f, 0x0e, 0x17, 0xb8, 0xd1, 0x02, 0x55, 0x54, 0xe1, 0xa2, 0x75, 0x2b, 0x8e, 0x96, 0x1b,
	0x26, 0x60, 0x12, 0xd9, 0x26, 0xbb, 0xc9, 0x4f, 0xe0, 0x67, 0xf1, 0xdb, 0xd0, 0x7e, 0x44, 0x4e,
	0xe0, 0xc4, 0x6d, 0xdf, 0x9b, 0x37, 0x1f, 0xef, 0x69, 0x21, 0xba, 0xaf, 0xe7, 0xcb, 0x4d, 0x7f,
	0xde, 0xaf, 0x3b, 0xd5, 0xe1, 0xd8, 0x22, 0xfe, 0x0a, 0xfc, 0xdb, 0x6e, 0x49, 0x2d, 0x3e, 0x03,
	0xf8, 0x21, 0xbb, 0xb6, 0x52, 0x1a, 0x25, 0x2c, 0x65, 0x59, 0x24, 0x02, 0xcd, 0x98, 0x32, 0x2f,
	0x61, 0x7c, 0xd9, 0xb5, 0x8b, 0xe6, 0x1b, 0xbe, 0x80, 0x70, 0x55, 0x4b, 0x55, 0xd9, 0x01, 0xc9,
	0x51, 0xca, 0x32, 0x4f, 0x80, 0xa6, 0x2e, 0x0c, 0x83, 0x19, 0xf8, 0x8b, 0x66, 0x45, 0x32, 0xf1,
	0x52, 0x2f, 0x0b, 0x73, 0x3c, 0x77, 0x8b, 0x6d, 0xf9, 0x63, 0xb3, 0x22, 0x61, 0x05, 0xfc, 0x37,
	0x03, 0x18, 0x58, 0x44, 0x38, 0xee, 0x6b, 0xf5, 0xdd, 0x2c, 0x0f, 0x84, 0x79, 0xe3, 0x53, 0x08,
	0xbe, 0xd6, 0x8a, 0x2a, 0x49, 0xd4, 0xba, 0x5d, 0x27, 0x9a, 0x28, 0x89, 0x5a, 0x7c, 0x0d, 0xbe,
	0x54, 0xb5, 0xa2, 0xc4, 0x4b, 0x59, 0x76, 0x9a, 0x3f, 0xff, 0x77, 0x93, 0x7b, 0x96, 0x5a, 0x25,
	0xac, 0x98, 0xcf, 0x20, 0xdc, 0x63, 0x31, 0x84, 0x07, 0x77, 0xc5, 0x75, 0x71, 0xf3, 0xa5, 0x98,
	0x8c, 0xf0, 0x11, 0xc4, 0xc5, 0xcd, 0x6d, 0x75, 0xf1, 0xee, 0xf2, 0xfa, 0xc3, 0xfb, 0xea, 0xee,
	0xf3, 0x84, 0x61, 0x0c, 0xc1, 0x00, 0x8f, 0xb4, 0xfc, 0xd3, 0xac, 0x2c, 0x67, 0xc5, 0xd5, 0xc4,
	0xe3, 0x53, 0x88, 0x4c, 0x3c, 0x82, 0x7e, 0x6e, 0x48, 0x2a, 0x7c, 0x09, 0xfe, 0x90, 0x5f, 0x98,
	0xc7, 0xbb, 0x83, 0xac, 0xc8, 0xd6, 0xf8, 0x43, 0x88, 0x5d, 0x93, 0xec, 0xbb, 0x56, 0x12, 0x3f,
	0x85, 0x48, 0x9f, 0x22, 0xdd, 0x14, 0x3e, 0x85, 0xd8, 0x61, 0x2b, 0x40, 0x6e, 0x7d, 0xca, 0x84,
	0x99, 0x44, 0xa3, 0xdd, 0x58, 0xad, 0xb2, 0xae, 0x24, 0x17, 0x70, 0xac, 0xe1, 0x90, 0x09, 0xfb,
	0x8f, 0x4c, 0xf0, 0x0c, 0xfc, 0x79, 0xb7, 0x69, 0x95, 0x89, 0xd8, 0x17, 0x16, 0xe4, 0xbf, 0x18,
	0xc4, 0x4e, 0x4c, 0xeb, 0x6d, 0x33, 0x27, 0x7c, 0x0b, 0x41, 0x59, 0x6f, 0xc9, 0x7e, 0x99, 0xb3,
	0x43, 0x7b, 0xf6, 0xfa, 0x27, 0x8f, 0xff, 0x62, 0x9d, 0xc9, 0x11, 0xbe, 0x81, 0x93, 0x2b, 0x52,
	0xc6, 0xd9, 0xd0, 0xba, 0x6f, 0x7c, 0x68, 0x3d, 0xb0, 0xcf, 0x47, 0xf7, 0x63, 0xf3, 0x69, 0xa7,
	0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xcf, 0x7d, 0xc1, 0xbb, 0xc4, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BackupServiceClient is the client API for BackupService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BackupServiceClient interface {
	SaveToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error)
	GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type backupServiceClient struct {
	cc *grpc.ClientConn
}

func NewBackupServiceClient(cc *grpc.ClientConn) BackupServiceClient {
	return &backupServiceClient{cc}
}

func (c *backupServiceClient) SaveToken(ctx context.Context, in *TokenRequest, opts ...grpc.CallOption) (*TokenResponse, error) {
	out := new(TokenResponse)
	err := c.cc.Invoke(ctx, "/backup.BackupService/SaveToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *backupServiceClient) GetStats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, "/backup.BackupService/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BackupServiceServer is the server API for BackupService service.
type BackupServiceServer interface {
	SaveToken(context.Context, *TokenRequest) (*TokenResponse, error)
	GetStats(context.Context, *StatsRequest) (*StatsResponse, error)
}

func RegisterBackupServiceServer(s *grpc.Server, srv BackupServiceServer) {
	s.RegisterService(&_BackupService_serviceDesc, srv)
}

func _BackupService_SaveToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).SaveToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.BackupService/SaveToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).SaveToken(ctx, req.(*TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BackupService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackupServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/backup.BackupService/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackupServiceServer).GetStats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackupService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "backup.BackupService",
	HandlerType: (*BackupServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveToken",
			Handler:    _BackupService_SaveToken_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _BackupService_GetStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backup.proto",
}
